// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cyryprxkhxadmfwhizjy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN5cnlwcnhraHhhZG1md2hpemp5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1NTgzMzQsImV4cCI6MjA2MDEzNDMzNH0.lIzZV-684CIHXGK0jPSYYaSLFSlABzd5XnzB5_FyfkA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);